version: '3.8'
volumes:
  rental_app_data:
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - rental_app_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root